### ISSUE TITLE
todo list

### ISSUE THREAD

**Issue by originals-tz** [WheelHome/Lab#1]
待协商：
- [ ] commit模板(将其作为git global hook)
- [ ] 代码规范
- [ ] 注释风格
- [ ] 测试工具 : 单元测试，性能测试
- [ ] 分支，提交，code review

**Comment by originals-tz** [comment]
## tool
错误码(errno)的查看工具/处理框架

**Comment by originals-tz** [comment]
lru缓存，然后根据规则将冷数据置换到leveldb中
